apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor-model
  labels:
    app: predictor-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictor-model
  template:
    metadata:
      labels:
        app: predictor-model
    spec:
      containers:
      - name: predictor-model
        image: axololtos/predictor-model:2.3
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: predictor-model-service
spec:
  selector:
    app: predictor-model
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
